
# Default config
wallpaper {
  monitor = eDP-1
  # path = /home/gn15h/wallpapers/ds2.jpg
  path = ~/wallpapers/G5wrilHbkAIdniy.jfif
  fit_mode = cover
}

# Two monitors (Uncomment for usage)
# wallpaper {
#   monitor = eDP-1
#   path = /home/gn15h/wallpapers/ds2.jpg
#   fit_mode = cover
# }
#
# wallpaper {
#   monitor = eDP-1
#   path = /home/gn15h/wallpapers/ds2.jpg
#   fit_mode = cover
# }
