
# preload = /home/gn15h/wallpapers/ds2.jpg
# wallpaper = , /home/gn15h/wallpapers/ds2.jpg
# wallpaper = , $BACKGROUND

wallpaper {
  monitor = eDP-1
  path = /home/gn15h/wallpapers/ds2.jpg
  fit_mode = cover
}
